let cfg={};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function money(v){return Number(v||0).toLocaleString('en-IN')}
async function load(){try{const r=await fetch('/api/public');const j=await r.json();cfg=j.settings||{};render()}catch(e){console.error(e)}}
function render(){const p=cfg;$('paymentDetails').innerHTML=`<div class="detail-row"><span class="detail-label">UPI ID</span><strong class="detail-value">${esc(p.upi)||'Not configured'}</strong></div><div class="detail-row"><span class="detail-label">Bank Name</span><strong class="detail-value">${esc(p.bank)||'Not configured'}</strong></div><div class="detail-row"><span class="detail-label">Account Number</span><strong class="detail-value">${esc(p.account)||'Not configured'}</strong></div><div class="detail-row"><span class="detail-label">IFSC Code</span><strong class="detail-value">${esc(p.ifsc)||'Not configured'}</strong></div>`;$('qrWrap').innerHTML=p.qr?`<img class="qr" src="${esc(p.qr)}" alt="Payment QR code"><div class="qr-caption">Scan this QR using your preferred UPI app</div>`:`<div class="qr-caption">QR code has not been configured yet.</div>`;$('instruction').textContent=p.message||'Please complete the payment within the specified limits and submit your UTR and screenshot.';$('limits').textContent=`Minimum ₹${money(p.min)}  •  Maximum ₹${money(p.max)}`;$('amount').min=Number(p.min||1);$('amount').max=Number(p.max||100000000);$('contacts').innerHTML=[p.whatsapp?`<a href="${esc(p.whatsapp)}" target="_blank" rel="noopener">WhatsApp Support ↗</a>`:'',p.telegram?`<a href="${esc(p.telegram)}" target="_blank" rel="noopener">Telegram Support ↗</a>`:''].join('')||'<span style="color:#777;font-size:12px">Support contacts are not configured yet.</span>'}
$('paymentForm').addEventListener('submit',async e=>{e.preventDefault();$('result').innerHTML='';const fd=new FormData(e.target);try{const r=await fetch('/api/payment',{method:'POST',body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error||'Submission failed');$('result').innerHTML=`<div class="result-box"><b>Payment details submitted successfully.</b><br>Your unique reference code is <strong>${esc(j.code)}</strong>.<br>Save this code and use it in the Check Payment Status section.</div>`;e.target.reset()}catch(err){$('result').innerHTML=`<div class="result-error">${esc(err.message)}</div>`}});
async function checkStatus(){const code=$('codeSearch').value.trim().toUpperCase();if(!code){$('statusResult').innerHTML='<div class="result-error">Please enter your unique reference code.</div>';return}$('statusResult').innerHTML='<div class="status-result">Checking latest status…</div>';try{const r=await fetch('/api/status/'+encodeURIComponent(code));const j=await r.json();if(!r.ok)throw new Error(j.error||'Transaction not found');const date=new Date(j.updated_at).toLocaleString();const reason=j.status==='rejected'&&j.rejection_reason?`<div class="status-meta"><b>Reason:</b> ${esc(j.rejection_reason)}</div>`:'';$('statusResult').innerHTML=`<div class="status-result"><div class="status-code">${esc(j.code)}</div><div style="margin:10px 0"><span class="pill ${esc(j.status)}">${esc(j.status)}</span></div><div class="status-meta">Amount: ₹${money(j.amount)}<br>Last updated: ${esc(date)}</div>${reason}</div>`}catch(err){$('statusResult').innerHTML=`<div class="result-error">${esc(err.message)}</div>`}}
load();
